name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Permisos necesarios para que GITHUB_TOKEN pueda escribir en la rama gh-pages
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Esta línea asegura que el Action solo se ejecute en el repositorio original y no en forks.
    # Reemplaza 'USUARIO' con el nombre del usuario u organización dueña del repositorio padre.
    if: github.repository == 'aprendamoszapoteco/aprendamoszapoteco.github.io'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installing NPM packages
        run: npm i

      - name: Building project
        run: npm run build

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # Se agrega también la condición aquí por seguridad
    if: github.ref == 'refs/heads/main' && github.repository == 'aprendamoszapoteco/aprendamoszapoteco.github.io'

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
